---
title: "Anna Beyeler"
author: "SBDM2025"
categories: ["Causal manipulations in decision making"]
image: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWFgbXQNhlZyYSJ3ZftaMc2mcgyhHHjHiVdA&s
description: "Neural Circuits of Anxiety, Neurocentre Magendie (Bordeaux, France)"
---

Session: Causal manipulations in decision making
Date & time: 16.06 - 15h10

Website: [https://neurocentre-magendie.fr/recherche/Beyeler/descriptionTeam.php](https://neurocentre-magendie.fr/recherche/Beyeler/descriptionTeam.php)

#### Dopamine transmission in the anterior insula shapes the neural coding of anxiety

The insular cortex (or insula), and particularly its anterior region, plays a crucial role in the control of emotional valence and anxiety. While dopamine neurotransmission is known to modulate anxiety levels in humans and animal models, its regulatory effects on the anterior insula remained unexplored. Here, using a multifaceted approach, we uncovered how dopamine shapes anterior insula function in anxiety-related behaviors. First, we reveal a high density of neurons expressing type-1 dopamine receptors (D1) in the insula, particularly important in the anterior section, and seven times greater than the density of neurons expressing type-2 dopamine receptors (D2). Importantly, few neurons co-expressed Drd1 and Drd2 mRNAs in the anterior and posterior insula, and the density of Drd1+ neurons in the anterior insula was twice higher among inhibitory neurons than excitatory neurons. We then found that pharmacological activation of D1 in the anterior insula is anxiogenic, supporting a causal link between insular dopamine signaling and anxiety-related behaviors. Consistently, using fiber-photometry recordings, we identified an increase of dopamine release onto D1+ neurons in the anterior insula while mice were located in anxiogenic spaces, and that the amplitude of this increase is positively correlated with mice level of anxiety. Using population dynamics and deep-learning analyses of single-unit recordings we uncovered distinct coding patterns between anxiety-provoking and safe environments. Remarkably, systemic D1 activation, which heightens anxiety-related behaviors, strengthen this population coding dichotomy, by increasing the variability of the neural code for protected spaces, while increasing the reliability of the neural coding of anxiogenic spaces. Altogether, our findings provide a new model of neural population coding of anxiety and unravel D1-dependent coding mechanisms in the mouse anterior insula. 

