---
title: "Jacob Bakermans"
author: "SBDM2025"
categories: ["Comparative decision across agents"]
image: https://cdn.bsky.app/img/avatar/plain/did:plc:angiv7da2g7u2nzirlrbu7ga/bafkreicboejjibt6gnhaoz3vwzkpbece6fjsb5xeh5uryrutu4k2qptyu4@jpeg
description: "IMPACT, University of Geneva (Switzerland)" 
---

Session: Comparative decision across agents
Date & time: 16.06 - 12h00
Title: TBA

Website: [https://scholar.google.com/citations?user=hOfs-WMAAAAJ&hl=en](https://scholar.google.com/citations?user=hOfs-WMAAAAJ&hl=en)

#### Replay in artificial and biological intelligence: learning, planning, and map construction.

Some of the most successful AI models for reinforcement learning rely on imagined experience, for example for planning or credit assignment. Neural replay, a phenomenon where rodents reactivate representations of remote locations in rapid sequences, suggests the existence of similar mechanisms in biological brains. Indeed, recent theories have shown how neural replay can implement such decision-making computations. Here, I will exploit the famous hippocampal capacities for episodic memory and scene construction to propose yet another function for replay: the composition of new cognitive maps through combinations of generalisable building blocks. I rely on replay as the mechanism for building these new combinations and storing them in memory. Computationally, this model explains how new plans can be rapidly constructed, to avoid online planning and credit assignment altogether. Empirically, it predicts new hippocampal spatial responses at locations that have been visited in replay. I will show evidence for this emergence of place fields in replay in a reanalysis of a memory-guided spatial navigation experiment. Together, these results show how replay may construct compositional cognitive maps to create memories of the future.
