---
title: "Julia Sliwa"
author: "SBDM2025"
categories: ["Social cognition and decision making across species"]
image: https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRyUFJwwz0sXIDx8R69bB4yehryzbZNtQ5Vfj7-J4CEiheixFQV
description: "Neurophysiology of Social Cognition, Paris Brain Institute (France)" 
---

Session: Social cognition and decision making across species
Date & time: 17.06 - 10h10

Website: [https://www.sliwalab.org/](https://www.sliwalab.org/)

#### From agents, to actions, to interactions, to societies: imaging the primate social brain

Recognizing agents, their interactions and their relationships is essential for understanding the world around us. Using functional Magnetic Resonance Imaging, we discovered in the macaque monkey brain a network of areas centered on the medial prefrontal cortex, ventrolateral prefrontal cortex, superior temporal sulcus, temporal pole and parietal area 7A, that is engaged in social interaction analysis. Its extent and location suggest that this function is an evolutionary forerunner of human mind-reading capabilities. A comparative fMRI investigation in humans additionally revealed which neural strategies adapted to the needs of each species, and emphasized human interest in understanding actions of our peers directed towards objects. Further by integrating the nature and frequency of interactions over time, relationships emerge. Kinship, hierarchy, and friendship are relationships that shape Primates structured societies. Preliminary brain imaging results in one rhesus macaque from a semi free-ranging group, suggest an encoding of social network topological variables.  Signal in pSTS, area 7a, precuneus, and dmPFC correlated with similarity in social distance; while vlPFC, vmPFC, and ACC in similarity in centrality. Together these studies show how our primate brains continuously process individuals and social scenes unwinding in front of us.